### ISSUE TITLE
WIP Builds

### ISSUE THREAD

**Issue by theboy181** [aldelaro5/Dolphin-memory-engine#29]
Would it be possible to have a WIP build posted here? The latest release crashes quite often when deleting items from the list.

**Comment by aldelaro5** [comment]
Please refer to issue #11 as I assume it is the same problem you would have,

Essentially, this problem is known, but even in `master`, it's not fixed yet.  I will defintely fix this on the next release.  The next release cycle should be start this summer, but I can't exactly tell when and I also have been busy so that explains why it has been known for a while.

For now, I will close this, but I suggest you subscribe for notifications on the issue I mentioned as it will be where I will tell when it is fixed in a commit.  As for the build, I won't provide builds other than release (as preparing them takes a bit), but if you want to have the commits early, please refer to the README for the build instructions.

**Comment by theboy181** [comment]
thank you for the update. I will look into installing a compiler soon.
