### ISSUE TITLE
Feature: Support any executable name

### ISSUE THREAD

**Issue by StackOverflow0x** [aldelaro5/dolphin-memory-engine#42]
Dolphin Memory Engine will not hook to Dolphin if the Dolphin executable is renamed. I maintain several Dolphin versions in the same folder and rename them to the version they are and if they are not explicitly named "dolphin.exe", then this tool won't hook to it.

**Comment by aldelaro5** [comment]
Yeah, it uses the name to tell that it is dolphin. Honestly, I am not sure if it's possible to detect the dolphin process other than its name, it seems to be the only distinguishing feature of them in the process list (or maybe I am missing something). The same would go on linux because I look up the command line which has the name of the elf so if you were to rename it, it would still treat it differently.

For now, can you use different dolphin's folders?  because I am not sure if it can be fixed reliably.

**Comment by StackOverflow0x** [comment]
What if, can there be a setting somewhere where the custom executable name can be specified so that it allows it to hook to it?
Otherwise, I could just keep a default name version just to use with this.

**Comment by aldelaro5** [comment]
It could work, whenever I come back to this (because this project does need more love tbh), I'll check on it!

**Comment by dreamsyntax** [comment]
Proposal:
* A default list of names in the `settings.ini` or possibly a new `targets.ini` file.
** Contain the known common dolphin process names (nogui, wx, qt, etc...)
* Allow for any process name to be added in this list.
* There will not be a GUI element for this (unless requested).

**Comment by cristian64** [comment]
Passing the alternative process name as an argument to DME could be another solution (e.g. `--dolphin-name`).

Examples:
- `dolphin-memory-engine` looks for `dolphin-emu`
- `dolphin-memory-engine --dolphin-name dolphin_backup.exe`

Then it would be easy to launch two DME that track different Dolphin instances.

**Comment by dreamsyntax** [comment]
> Passing the alternative process name as an argument to DME could be another solution (e.g. `--dolphin-name`).
> 
> Examples:
> 
>     * `dolphin-memory-engine` looks for `dolphin-emu`
> 
>     * `dolphin-memory-engine --dolphin-name dolphin_backup.exe`
> 
> 
> Then it would be easy to launch two DME that track different Dolphin instances.

I'd be fine with that too.

**Comment by cristian64** [comment]
I'll look into this later today.
