### ISSUE TITLE
Any chance of getting the mem management parts of this as a dynamic lib?

### ISSUE THREAD

**Issue by JillCrungus** [aldelaro5/Dolphin-memory-engine#43]
I'm currently working on another project (in C#, so just copying the code doesn't really work out) that requires hooking into Dolphin and accessing GameCube memory during emulation.

Figuring out where the GC memory space starts is the hard part, but this program seems to be capable of doing that. So I was wondering if it'd be possible to get those parts as a dynamic library so that other programs can make use of the functionality? Perhaps it'd be useful to have a function in the library that you can pass a process handle to and get the memory address where GC memory starts returned (or 0 if emulation has not started).

Having this in a dynamic lib would allow me to use P/Invoke to call the function from C#, but of course would make things easier for people potentially working on other projects (Whether they be C# or C++) with similar requirements.

Obviously this is a bit of a big ask for something so specific, but I figured I'd ask anyway before attempting it (and no doubt botching it) myself. Thanks.

**Comment by aldelaro5** [comment]
sorry to take so long to answer, but the basic idea is not necessarly planning it.

The reason is the code to do it is....rather simple in fact, it's imo TOO simple. The issue is it's limited: it only gives you access to the main memory like 75% of the games. This was the only way I knew to do IPC at the time so i went for it and for a lot of use case, it does a pretty good job, but honestly, I need to redo the IPC entirely.

However, I might not even get to do it because what I plan to do is to ATTEMPT (no idea if I will succeed) to merge the feature of this program into Dolphin. About a month ago, I had a chat with some dolphin devs and I was surprised to hear that they think it can be possible without impacting the perf too much (it would be an opt in if it does though which I am fine with). The plan is to start the efforts next summer.

If this succeed, the sky would be the limit: you could be able to check EVERY ram region for potentially every game, there might even be potential for full MMU games to work, but this is going to require a lot of work. It would also guarantee much more stability and have more features potential. 

Unfortunately, due to being busy with reversing project, I do not plan to work on this until next summer.

So this is why I say it's not currently planned as I might redo the entire IPC or I don't and you won't need this because it would be inside dolphin anyway.
