### ISSUE TITLE
MEM2 Wii only RAM not found even when playing Wii games

### ISSUE THREAD

**Issue by JoshuaMKW** [aldelaro5/Dolphin-memory-engine#46]
I think it may be due to Dolphin's updates, but as of a few weeks ago it stopped being able to view the Wii only RAM at +0x90000000. It always says that the memory region is absent.

**Comment by JoshuaMKW** [comment]
As of now, I know that this issue is caused by Dolphin builds using vs code 2019 solutions

**Comment by aldelaro5** [comment]
If I come back to this, I have to retest current builds, it's been so long and Dolphin progresses very fast :(

**Comment by patrickriordan** [comment]
I also ran into this issue. Seems to have started happening between versions dolphin-master-5.0-11333 (working) and dolphin-master-5.0-11608 (not working). I thought that 11333 was when they added vscode 2019...

**Comment by PPLToast** [comment]
Bisected to https://github.com/dolphin-emu/dolphin/pull/8537

**Comment by NicholasMoser** [comment]
I'm going to try and fix this. My current understanding appears to be that because the fastmem arena construction is out of the memory mapper, MEM2 may no longer be directly after MEM1 in memory.

Therefore this assumption may no longer be true: https://github.com/aldelaro5/Dolphin-memory-engine/blob/9e80462b7aa7a2b002843dd3cd9b3e2f45d0c9e0/Source/DolphinProcess/DolphinAccessor.cpp#L110

So we likely will have to search for MEM2 similar to how MEM1 is searched for.
Linux: https://github.com/aldelaro5/Dolphin-memory-engine/blob/9e80462b7aa7a2b002843dd3cd9b3e2f45d0c9e0/Source/DolphinProcess/Linux/LinuxDolphinProcess.cpp#L55
Windows: https://github.com/aldelaro5/Dolphin-memory-engine/blob/9e80462b7aa7a2b002843dd3cd9b3e2f45d0c9e0/Source/DolphinProcess/Windows/WindowsDolphinProcess.cpp#L92
